-----------------------------------
-- Indexation(target, reference) --
-- └── Effect(			 --
--       GrowthRate target,	 --
--       GrowthRate reference	 --
--     )			 --
-----------------------------------
